config/routes.rb
RedmineApp::Application.routes.draw do
  get '/link/dialog', to: 'link#dialog'
  get '/link/autocomplete', to: 'link#autocomplete'
  post '/link/share', to: 'link#share'
end

app/models/link_mailer.rb
class LinkMailer < Mailer
  def self.deliver(users, project, obj, url, comment)
    from = User.current

    users.each do |to|
      share(to, from, project, obj, url, comment).deliver_later
    end
  end

  def share(to, from, project, obj, url, comment)
    redmine_headers 'Project' => project.identifier

    @author = from
    @record = record(obj)
    @url = url
    @comment = comment

    s = l(:share_label_subject, sender: from.name, record: @record)

    mail to: to, subject: "[#{project.name}] #{s}"
  end

  def record(obj)
    case obj.class.name
    when 'Issue'
      l(:label_issue)
    when 'Wiki'
      l(:label_wiki)
    when 'News'
      l(:label_news)
    when 'Document'
      l(:label_document)
    when 'Board'
      l(:label_board)
    when 'Repository::Git', 'Repository::Subversion', 'Repository::Mercurial'
      l(:label_repository)
    when 'Version'
      l(:label_version)
    else
      l(:share_label_page)
    end
  end
end

app/controllers/link_controller.rb
class LinkController < ApplicationController
  TERM_LEN_PUB_PROJ_MIN = 2
  AUTOCOMPLETE_NUM_MAX = 20
  AVATAR_SIZE = 16

  before_action :require_login

  def dialog
    @project_id = params[:project_id]
    @object_type = params[:object_type]
    @object_id = params[:object_id]
  end

  def share
    url = params[:url]

    proj = Project.find(params[:project_id])
    obj = find_object(params[:object_type], params[:object_id])

    raise unless authorized?(proj)

    ids = params[:recipients].split(',')
    recipients = User.active.visible.where(id: ids.flatten.compact.uniq)

    # Exclude non-members
    recipients &= proj.users unless proj.is_public

    LinkMailer.deliver(recipients, proj, obj, url, params[:comment])

    flash[:notice] = l(:share_notice_email_sent)
    redirect_to_referer_or url
  rescue
    flash[:error] = l(:share_notice_email_error)
    redirect_to_referer_or url
  end

  def autocomplete
    term = params[:term]

    proj = Project.find(params[:project_id])

    raise unless authorized?(proj)

    scope = (proj.is_public && (term.length >= TERM_LEN_PUB_PROJ_MIN)) ?
              User.all : proj.users

    users = scope.active.visible.sorted.like(term)
              .where.not(id: params[:exclude])
              .limit(AUTOCOMPLETE_NUM_MAX).to_a

    render json: users.map {|user|
      {
        value: user.name.to_s,
        label: user.name.to_s,
        id: user.id.to_s,
        avatar: avatar_image_tag(user)
      }
    }
  rescue
    render_error status: 403
  end

  def authorized?(project)
    User.current.allowed_to?({controller: 'projects', action: 'show'}, project)
  end

  def find_object(object_type, object_id)
    Object.const_get(object_type.camelcase).where(id: Array.wrap(object_id))
      .to_a.first
  rescue
    nil
  end

  def avatar_image_tag(user)
    avtr = view_context.avatar(user, size: AVATAR_SIZE.to_s)

    avtr.blank? ?
      view_context.image_tag('default.png', plugin: 'redmine_share',
                             size: AVATAR_SIZE.to_s, class: 'gravatar') :
      avtr
  end
end

app/views/link/_dialog.html.erb
<%= form_tag(link_share_path, method: :post, id: 'redmine-share-form') do %>
<%= hidden_field_tag 'url', '' %>
<%= hidden_field_tag 'project_id', project_id %>
<%= hidden_field_tag 'object_type', object_type %>
<%= hidden_field_tag 'object_id', object_id %>

<p>
  <%= label_tag 'principal_search', l(:label_user_search) %>
  <%= text_field_tag 'principal_search', nil %>
</p>

<%= label_tag 'recipients', l(:share_label_with) %>
<%= hidden_field_tag 'recipients', '' %>
<ul id="redmine-share-with"></ul>

<p>
  <%= label_tag 'comment', l(:label_comment) %>
  <%= text_area_tag 'comment', nil %>
</p>

<p class="buttons">
  <%= submit_tag l(:share_button), name: nil, id: 'redmine-share-submit' %>
  <%= link_to l(:button_cancel), '#', id: 'redmine-share-cancel' %>
</p>
<% end %>

app/views/link/dialog.js.erb
$('#redmine-share-dialog').html(
  '<%= escape_javascript render(partial: 'link/dialog', locals: {
                                  project_id: @project_id,
                                  object_type: @object_type,
                                  object_id: @object_id}) %>'
);

$('#redmine-share-submit').prop('disabled', true);

observeAutocompleteField(
  'principal_search',
  function(request, response) {
    var recipients = $('#redmine-share-with li').map(function() {
      return $(this).data('uid');
    }).get();

    $.ajax({
      url: '<%= escape_javascript link_autocomplete_path %>',
      dataType: 'json',
      type: 'GET',
      cache: false,
      data: {
        term: request.term,
        project_id: '<%= @project_id %>',
        exclude: recipients
      },
      success: function(data) {
        response(data);
      },
      error: function(XMLHttpRequest, textStatus, errorThrown) {
        response(['']);
      }
    });
  }, {
    appendTo: '#redmine-share-dialog',
    autoFocus: true,
    minLength: 0,
    select: function(event, ui) {
      $('#redmine-share-with').append(
        '<li data-uid="' + ui.item.id + '">' + ui.item.avatar + ' ' +
          ui.item.label + '<a class="delete icon-only icon-del" href="#">' +
          '<%= l(:button_delete) %></a></li>');
      $('#redmine-share-submit').prop('disabled', false);
      $('#principal_search').addClass('redmine-share-selected');
    },
    close: function(event, ui) {
      if ($('#principal_search').hasClass('redmine-share-selected')) {
        // Clear search form
        $('#principal_search').val('');
        $('#principal_search').removeClass('redmine-share-selected');
      }
    }
  }
);

$('#redmine-share-form input:hidden[name="url"]').val(location.href);

$('#redmine-share-with').on('click', 'a.delete', function(e) {
  e.preventDefault();
  $(e.currentTarget).parent().remove();

  if ($('#redmine-share-with li').length == 0) {
    $('#redmine-share-submit').prop('disabled', true);
  }
});

$('#redmine-share-submit').on('click', function(e) {
  var recipients = $('#redmine-share-with li').map(function() {
    return $(this).data('uid');
  }).get().join(',');

  $('#redmine-share-form input:hidden[name="recipients"]').val(recipients);

  $('#redmine-share-dialog').dialog('close');
});

$('#redmine-share-cancel').on('click', function(e) {
  e.preventDefault();
  $('#redmine-share-dialog').dialog('close');
});

$('#redmine-share-dialog').dialog({
  modal: true,
  draggable: true,
  dialogClass: 'modal',
  title: '<%= l(:share_title) %>',
  width: 'auto'
});

$('#principal_search').on('keydown', function(e) {
  // Disable submit by enter key
  return (e.which !== 13) && (e.keyCode !== 13);
}).on('click', function(e) {
  // Shows selection
  var event = $.Event('keydown');
  event.keyCode = 40;
  $('#principal_search').trigger(event);
});

app/views/redmine_share/_body.html.erb
<% if @project && User.current.login?
     obj = @issue || @wiki || @page || @news || @document || @topic ||
       @board || @repository || @version || nil %>
<div id="redmine-share-dialog" style="display: none"></div>
<script>
$(function() {
  $('#content > .contextual').append(
    '<%= escape_javascript render(
      partial: 'redmine_share/contextual',
      locals: {project: @project, object: obj}) %>');
});
</script>
<% end %>

app/views/redmine_share/_contextual.html.erb
<%= link_to l(:share_button),
      link_dialog_path(
        project_id: project,
        object_type: object ? object.class.name.underscore : nil,
        object_id: object),
      remote: true,
      method: 'get',
      class: 'icon icon-share' %>

app/views/redmine_share/_header.html.erb
<% if @project %>
<%= stylesheet_link_tag 'redmine-share.css', plugin: 'redmine_share' %>
<% end %>